apiVersion: v1
kind: PersistentVolume
metadata:
  name: existing-backup-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: freenas-iscsi-csi
  csi:
    driver: org.democratic-csi.iscsi
    volumeHandle: existing-backup-volume-id  # ID of your existing volume on FreeNAS
    volumeAttributes:
      fs_type: ext4
