apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: freenas-iscsi-csi
  volumeName: existing-backup-pv
