apiVersion: batch/v1
kind: CronJob
metadata:
  name: windows-backup-cronjob
spec:
  schedule: "0 0 31 2 *"  # A non-recurring time (e.g., Feb 31st)
  suspend: true  # Prevents the job from running automatically
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: registry.desku.be/epheo/borgbackup:latest
            env:
            - name: BORG_CONFIG_DIR
              value: /tmp/borg_config
            - name: BORG_CACHE_DIR
              value: /tmp/borg_cache
            - name: BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK
              value: "yes"
            command: ["/bin/bash", "-c"]
            args:
              - |
                echo "Starting Windows Backup pod with two mounted PVCs"
                mkdir -p $BORG_CONFIG_DIR $BORG_CACHE_DIR
                borg init --encryption=none /backup/
                borg create --read-special /backup::"backup-$(date +%Y-%m-%d_%H-%M-%S)" /dev/windows-block
            volumeDevices:
            - devicePath: /dev/windows-block
              name: windows-block
            volumeMounts:
            - mountPath: /backup
              name: windows-backup
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "2"
          restartPolicy: OnFailure
          volumes:
          - name: windows-block
            persistentVolumeClaim:
              claimName: windows
          - name: windows-backup
            persistentVolumeClaim:
              claimName: windows-backup