apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
  namespace: epheo
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          model: host-passthrough
          sockets: 2
          threads: 1
        features:
          acpi: {}
          smm:
            enabled: true 
        firmware:
          bootloader:
            efi:
              secureBoot: false # For Nvidia Driver...
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: pvdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          autoattachGraphicsDevice: false
          gpus:
          - deviceName: nvidia.com/GA102_GEFORCE_RTX_3080
            name: gpuvideo
          hostDevices:
          - deviceName: devices.kubevirt.io/USB3_Controller
            name: usbcontroller
          - deviceName: devices.kubevirt.io/USB3_Controller
            name: usbcontroller2
          - deviceName: intel.com/WIFI_Controller
            name: wificontroller
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            model: virtio
            name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      hostname: fedora
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: br1
        name: nic-0
      terminationGracePeriodSeconds: 0
      volumes:
        - persistentVolumeClaim:
            claimName: 'fedora35'
          name: pvdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk
